---
sudo: required
services: docker
language: generic
dist: xenial

branches:
  only:
  - master
  - travis

jobs:
  include:
    - stage: tests
      script:
      - |
        if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
          make travis-publish
        else
          make travis-runtests
        fi
